plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-android-extensions'
    id 'kotlin-kapt'
    id 'org.jetbrains.kotlin.android'
}


apply from: '../wongxd/config.gradle'
//读取Git commit number
static def getGitCommitNumber() {
//    return 'git rev-list HEAD --first-parent --count'.execute().text.trim().toInteger()
    return 0
}


//读取Git Tag
static def getGitTag() {
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'describe', '--tags'
            standardOutput = stdout
        }
        return stdout.toString().trim()
    }
    catch (ignored) {
        return "1.0.3"
    }
}


//读取Git日志
static def getGitVersionInfo() {
    return 'git rev-parse --short HEAD'.execute().text.trim()
}


android {

    defaultConfig {
        applicationId "com.xianglilai.lixianghuandian"
        versionCode 33
        versionName "1.0.33"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        ndk {
            //选择要添加的对应cpu类型的.so库。
            abiFilters "armeabi-v7a", "arm64-v8a"//"armeabi",
        }
    }


    signingConfigs {
        debug {
            storeFile file("lxhd.jks")
            storePassword "123456"
            keyAlias "lxhd"
            keyPassword "123456"
        }
        release {
            storeFile file("lxhd.jks")
            storePassword "123456"
            keyAlias "lxhd"
            keyPassword "123456"
        }
    }


    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            signingConfig signingConfigs.release
        }
    }


    android.applicationVariants.all { variant ->
        variant.outputs.all {
            //def date = new Date().format("yyyyMMdd" , TimeZone.getTimeZone("Asia/Shanghai"))
//            def date = new Date().format("yyyy-MM-dd hh.mm", TimeZone.getTimeZone("GMT+08"))
            if (variant.buildType.name == 'debug') {
                outputFileName = "锂享换电_${versionName}-debug.apk"
            }
            if (variant.buildType.name == 'release') {
//                outputFileName = "享锂来租赁_${date}_${versionName}-release.apk"
                outputFileName = "锂享换电_${versionName}.apk"
            }
        }
    }


    sourceSets {
        main {

            java.srcDir("src/main/agent/java")
            res.srcDir("src/main/agent/res")


            java.srcDir("src/main/java")
            res.srcDir("src/main/res")

            def dirs = [
                    'custom', 'home', 'nearby', 'net_station', 'msg', 'shop', 'me'
            ]
            dirs.each { dir ->
                res.srcDir("src/main/$dir/res")
            }

        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }
}

dependencies {
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'

    api project(':wongxd')
    implementation 'com.contrarywind:Android-PickerView:4.1.9'
    implementation 'com.flyco.roundview:FlycoRoundView_Lib:1.1.4@aar'
    //高德地图
    //定位
    //noinspection GradleDependency
    api 'com.amap.api:location:5.4.0'
    //搜索
    //noinspection GradleDependency
    api 'com.amap.api:search:7.9.0'
    //3D地图
    //noinspection GradleDependency
    api 'com.amap.api:3dmap:8.0.0'
//    api 'com.amap.api:map2d:6.0.0'
    implementation 'io.github.lwjfork:CodeEditText:1.0.5'
    implementation files('libs/Amap_2DMap_V5.2.0_20170627.jar')
    implementation 'com.tencent.bugly:crashreport:latest.release'
    //网易一键登录
    implementation 'io.github.yidun:quicklogin:3.4.3'
    //图片选择器
    implementation 'io.github.lucksiege:pictureselector:v3.11.1'
    //轮播图
    implementation 'io.github.youth5201314:banner:2.2.3'
    //大图预览
    implementation 'com.github.OneZeroYang:PreviewPictureView:1.1.0'
    implementation 'com.github.chrisbanes:PhotoView:2.0.0'

    // ========== AdScope聚合广告SDK依赖 ==========
    // 接入AdScope聚合必须的aar包
    implementation(name: 'AMPSSDK-5.1.0.26', ext: 'aar')
    implementation(name: 'common_5.1.0.26', ext: 'aar')

    // 倍孜适配器包
    implementation(name: 'AMPSBZAdapter-5.1.490436.2', ext: 'aar')
    implementation(name: 'beizi_ad_sdk_3.5.0.43', ext: 'aar')
    // 倍孜广告渠道sdk特有aar包
    implementation(name: 'beizi_fusion_sdk_4.90.4.43', ext: 'aar')

    // 广点通（优量汇）适配器包
    implementation(name: 'AMPSGDTAdapter-5.1.46201490.1', ext: 'aar')
    // 广点通（优量汇）广告渠道sdk特有aar包
    implementation(name: 'GDTSDK.unionNormal.4.620.1490', ext: 'aar')

    // 快手适配器包
    implementation(name: 'AMPSKSAdapter-5.1.3374.1', ext: 'aar')
    // 快手广告渠道SDK特有aar包
    implementation(name: 'kssdk-ad-3.3.74-publishRelease-46670ffc8e', ext: 'aar')

    // 穿山甲适配器包 穿山甲和GroMore是同一个SDK，集成的时候穿山甲适配器和GroMore适配器二选一
    implementation(name: 'AMPSCSJAdapter-5.1.6607.1', ext: 'aar')
    implementation(name: 'open_ad_sdk_6.6.0.7', ext: 'aar')

    // support库依赖，SDK内部依赖如下support，请确保添加  （倍孜 快手 百度 需要添加这个）
    def support_version = "28.0.0" //建议使用的26以上的support库版本，建议使用28最新的即可。
    implementation "com.android.support:appcompat-v7:$support_version"

//    //3D地图so及jar
//    implementation 'com.amap.api:3dmap:latest.integration'
//    //定位功能
//    compileOnly 'com.amap.api:location:latest.integration'
//    //搜索功能
//    implementation 'com.amap.api:search:latest.integration'

//    implementation("com.aliyun.ams:alicloud-android-push:3.1.6") {
//        exclude group: 'com.ta.utdid2' //by group
//        exclude group: 'com.aliyun.ams', module: 'alicloud-android-utdid'
//    }

}